export const TECHNOLOGY_COLORS = {
  Solar: "#2d475a",
  Wind: "#46647b",
  "Non-Metallic": "#faecdb",
  Cement: "#104c3e",
  Paper: "#ab8933",
  Metals: "#cfb793",
  "Chemicals/Petchem": "#507867",
  Refinery: "#faeec3",
  "Power Plant: Coal": "#c6aa3d",
  "Power Plant: NG": "#e9cd49",
  "Green: Hydrogen: Refinery": "#623b34",
  "Blue: Hydrogen: Refinery": "#a3bcd3",
  Biomass: "#46647b",
  Biomethane: "#7891aa",
  "Natural Gas": "#eddabd",
  "Heat Pumps": "#947c5c",
  "Electric Boilers": "#83ac9a",
  "Electric Furnances": "#bbcaba",
  "Energy efficiency": "#dce2d6",
  "Process Optimization": "#2d475a",
  Affrorestation: "#2d475a",
  "Carbon Credits": "#dce5ea",
};