export const COLOR_DASHBOARD3 ={
    "Lever 1": {
        "Low-Carbon Feedstock":"#640a40",
        "Process Optimization":"#ba749f",
        "Solar":"#d9abc6",
        "Energy efficiency":"#ab8933",
        "Affrorestation":"#2d475a",
        "CCUS" :"#a3bcd3",
        "Wind":"#eed6e5",
        "Process / product redesign":"#973b74",
        "Green: Hydrogen":"#dce5ea",
        "Carbon Credits":"#7891aa",
        "Blue: Hydrogen":"#46647b",
    },
    "Lever 2": {
        "Process Optimization":"#ba749f",
        "Solar":"#d9abc6",
        "Energy efficiency":"#ab8933",
        "Affrorestation":"#2d475a",
        "CCUS":"#a3bcd3",
        "Wind":"#eed6e5",
        "NG to Bio methane":"#507867",
        "NG to Bio mass":"#104c3e",
        "Heat Pumps":"#faeec3",
        "Green: Hydrogen":"#dce5ea",
        "Electric Furnances":"#f2de8a",
        "Electric Boilers":"#e9cd49",
        "Coal to NG":"#c6aa3d",
        "Carbon Credits":"#7891aa",
        "Blue: Hydrogen":"#46647b",
    },
}
